-- Agregar columnas faltantes a la tabla loans
ALTER TABLE loans ADD COLUMN IF NOT EXISTS bank TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS collection_day INTEGER;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS start_date DATE;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS end_date DATE;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS opening_commission NUMERIC;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS early_repayment NUMERIC;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS delay_interest NUMERIC;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS subrogation NUMERIC;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS novation NUMERIC;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS valuation NUMERIC;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS insurance NUMERIC;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS cancellation NUMERIC;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS study NUMERIC;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS notes TEXT;
ALTER TABLE loans ADD COLUMN IF NOT EXISTS loan_type TEXT;