
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://eoupodozovwxbldzptlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvdXBvZG96b3Z3eGJsZHpwdGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5ODM1MjksImV4cCI6MjA4OTU1OTUyOX0.UpFH455mX_JED7aY0qjMVvz5dGYe9gIfvpP3P_25A7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
